# Generated by Django 5.1.7 on 2025-03-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolov12_detect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yolodetection',
            name='class_counts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yolodetection',
            name='total_detections',
            field=models.IntegerField(default=0),
        ),
    ]
