# Generated by Django 5.1.7 on 2025-04-04 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolov12_detect', '0003_detectionimage_yolomodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiWeightDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yolov12_detect.detectionimage')),
            ],
        ),
        migrations.CreateModel(
            name='MultiWeightDetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('detection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yolov12_detect.yolodetection')),
                ('parent_detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='yolov12_detect.multiweightdetection')),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yolov12_detect.yolomodel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
