# Generated by Django 5.1.7 on 2025-04-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolov12_detect', '0004_multiweightdetection_multiweightdetectionresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiweightdetection',
            name='resize_height',
            field=models.PositiveIntegerField(default=640),
        ),
        migrations.AddField(
            model_name='multiweightdetection',
            name='resize_width',
            field=models.PositiveIntegerField(default=640),
        ),
        migrations.AddField(
            model_name='yolodetection',
            name='resize_height',
            field=models.PositiveIntegerField(default=640),
        ),
        migrations.AddField(
            model_name='yolodetection',
            name='resize_width',
            field=models.PositiveIntegerField(default=640),
        ),
    ]
